services:
  postgres1:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=studio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres!
    ports:
      - "5432:5432"
    networks:
      - local_network

#  keycloak:
#
#    image: keycloak/keycloak:26.1.4
#    environment:
#      KC_HOSTNAME: localhost
#      KC_HOSTNAME_PORT: 8080
#      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HEALTH_ENABLED: "true"
#      KC_LOG_LEVEL: info
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
#      interval: 15s
#      timeout: 2s
#      retries: 15
#    command: ["start-dev", "--http-port", "8080"]
#    ports:
#      - "8080:8080"
#    networks:
#      - local_network
networks:
  local_network:
    driver: bridge
